port: 7880

rtc:
  port_range_start: 60000
  port_range_end: 60200
  use_external_ip: false
  node_ip: "127.0.0.1"

redis:
  address: redis:6379

keys:
  devkey: this-is-my-very-long-secret-key-123456

logging:
  level: info
