# /home/ubuntu/src/a501test/FE/docker-compose.yml
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://spring-app:8080
      - TZ=Asia/Seoul
    networks:
      - app-net
    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://127.0.0.1:3000',r=>process.exit(r.statusCode>=200&&r.statusCode<500?0:1)).on('error',()=>process.exit(1))"
        ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

networks:
  app-net:
    external: true
