"""
Call the AI server /api/v1/analysis/start using tokens.json generated by gen_tokens.py.
"""

import argparse
import json
from pathlib import Path

import httpx


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--tokens", default="artifacts/smoke/tokens.json")
    p.add_argument("--ai-url", default="http://localhost:8000")
    p.add_argument("--session-id", type=int, default=999999)
    p.add_argument("--participant-name", default="ai-agent-smoke")
    args = p.parse_args()

    tokens = json.loads(Path(args.tokens).read_text(encoding="utf-8"))
    room = tokens["room"]
    ai_token = tokens["ai_token"]

    payload = {
        "room_name": room,
        "token": ai_token,
        "session_id": args.session_id,
        "participant_name": args.participant_name,
    }

    url = args.ai_url.rstrip("/") + "/api/v1/analysis/start"
    print(f"[call_analysis_start] POST {url}")
    print(f"[call_analysis_start] payload.room_name={room}")

    with httpx.Client(timeout=10.0) as client:
        r = client.post(url, json=payload)
        print(f"[call_analysis_start] status={r.status_code}")
        print(r.text)


if __name__ == "__main__":
    main()
